# Generated by Django 6.1 on 2026-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFundConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=64, unique=True, verbose_name='交易账户ID')),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='账户总资金')),
                ('source', models.CharField(choices=[('manual', '手工维护'), ('gm', 'gm 同步')], default='manual', max_length=10, verbose_name='资金来源')),
                ('capital_basis', models.CharField(choices=[('total', '账户总资产（账面资金 + 持仓市值）'), ('cash', '账面资金（忽略持仓市值）'), ('available', '券商可用资金（最保守）')], default='total', max_length=10, verbose_name='额度口径')),
                ('available_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='券商可用资金')),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='持仓市值')),
                ('frozen_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='冻结资金')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
            ],
            options={
                'verbose_name': '账户资金配置',
                'verbose_name_plural': '账户资金配置',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('order_failed', '订单失败'), ('suite_failed', '策略执行失败'), ('plan_failed', '计划执行失败'), ('risk_violation', '风控违规'), ('system_error', '系统错误')], max_length=50, verbose_name='告警类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决')], default='pending', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='详细消息')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='错误代码')),
                ('in_app_notified', models.BooleanField(default=False, verbose_name='应用内已通知')),
                ('email_notified', models.BooleanField(default=False, verbose_name='邮件已通知')),
                ('notification_error', models.TextField(blank=True, verbose_name='通知错误信息')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
            },
        ),
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('in_app', '应用内通知'), ('email', '邮件通知')], max_length=20, unique=True, verbose_name='渠道类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('email_recipients', models.JSONField(blank=True, default=list, verbose_name='邮件收件人列表')),
                ('email_subject_prefix', models.CharField(default='[量化交易系统]', max_length=50, verbose_name='邮件主题前缀')),
                ('min_severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='low', max_length=20, verbose_name='最低告警级别')),
                ('alert_types', models.JSONField(blank=True, default=list, verbose_name='告警类型白名单（空表示全部）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '告警渠道配置',
                'verbose_name_plural': '告警渠道配置',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTypeRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='事件类型名')),
                ('scope', models.CharField(choices=[('system', '系统内置'), ('plugin', '插件定义'), ('user', '用户自定义')], default='user', max_length=20)),
                ('plugin_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源插件')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('payload_schema', models.JSONField(blank=True, default=dict, verbose_name='载荷 JSON Schema')),
                ('base_event_type', models.CharField(blank=True, help_text='用户自定义事件必须叠加在系统自带事件之上（base_event_type 为系统内置事件名）；插件事件可选叠加。', max_length=50, null=True, verbose_name='叠加基事件')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '事件类型注册',
                'verbose_name_plural': '事件类型注册',
                'db_table': 'execution_event_type_registry',
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('final_direction', models.SmallIntegerField(choices=[(-1, '卖出/做空'), (0, '观望/平仓'), (1, '买入/做多')])),
                ('node_snapshots', models.JSONField(blank=True, default=dict)),
                ('error_msg', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('blocked', '风控拦截')], default='success', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('plan', 'Plan 级'), ('suite', 'Suite 级'), ('case', 'Case 级')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='申请额度')),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='已占用金额')),
                ('status', models.CharField(choices=[('active', '生效中'), ('released', '已释放')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('suite', 'Suite 节点'), ('case', 'Case 节点')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20)),
                ('direction', models.SmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.PositiveIntegerField()),
                ('filled_volume', models.PositiveIntegerField(default=0)),
                ('external_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('filled', '已成交'), ('rejected', '已拒绝'), ('canceled', '已撤单')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('report_payload', models.JSONField(blank=True, default=dict)),
                ('processed_report_keys', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiteRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='标的代码')),
                ('status', models.CharField(choices=[('pending', '待启动'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20)),
                ('event_queue', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
