# Generated by Django 6.1 on 2026-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INIT', '初始化事件'), ('TIME', '定时事件'), ('CASE_START', 'Case 开始'), ('CASE_COMPLETED', 'Case 完成'), ('CASE_FAILED', 'Case 失败'), ('CASE_SKIPPED', 'Case 跳过'), ('SUITE_COMPLETED', 'Suite 完成'), ('CUSTOM', '自定义事件')], max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('final_direction', models.SmallIntegerField(choices=[(-1, '卖出/做空'), (0, '观望/平仓'), (1, '买入/做多')])),
                ('node_snapshots', models.JSONField(blank=True, default=dict)),
                ('error_msg', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('blocked', '风控拦截')], default='success', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('filled', '已成交'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiteRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='标的代码')),
                ('status', models.CharField(choices=[('pending', '待启动'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20)),
                ('event_queue', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
