# Generated by Django 6.1 on 2026-09-28 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('execution', '0001_initial'),
        ('plans', '0001_initial'),
        ('suites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='cases.case'),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='suites.suite'),
        ),
        migrations.AddField(
            model_name='noderun',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_runs', to='cases.case'),
        ),
        migrations.AddField(
            model_name='noderun',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='execution.noderun'),
        ),
        migrations.AddField(
            model_name='noderun',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_runs', to='suites.suite'),
        ),
        migrations.AddField(
            model_name='order',
            name='fund_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='execution.fundallocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='execution.executionlog'),
        ),
        migrations.AddField(
            model_name='alert',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='execution.order'),
        ),
        migrations.AddField(
            model_name='suiterun',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='suiterun',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='suites.suite'),
        ),
        migrations.AddField(
            model_name='noderun',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='execution.suiterun'),
        ),
        migrations.AddField(
            model_name='event',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='execution.suiterun'),
        ),
        migrations.AddField(
            model_name='alert',
            name='suite_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='execution.suiterun'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['symbol', '-trigger_time'], name='execution_e_symbol_32ccf1_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['plan', '-trigger_time'], name='execution_e_plan_id_2065f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'plan')), fields=('plan',), name='unique_plan_level_allocation'),
        ),
        migrations.AddConstraint(
            model_name='fundallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'suite')), fields=('plan', 'suite'), name='unique_suite_level_allocation'),
        ),
        migrations.AddConstraint(
            model_name='fundallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'case')), fields=('plan', 'suite', 'case'), name='unique_case_level_allocation'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='execution_a_created_ea3862_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='execution_a_status_3bd8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', '-created_at'], name='execution_a_alert_t_45695e_idx'),
        ),
    ]
