# Generated by Django 6.1 on 2026-08-24 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0002_initial'),
        ('suites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiterun',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='suites.suite'),
        ),
        migrations.AddField(
            model_name='event',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='execution.suiterun'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['symbol', '-trigger_time'], name='execution_e_symbol_32ccf1_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['plan', '-trigger_time'], name='execution_e_plan_id_2065f1_idx'),
        ),
    ]
