# Generated by Django 6.1 on 2026-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='事件类型名')),
                ('scope', models.CharField(choices=[('system', '系统内置'), ('plugin', '插件定义'), ('user', '用户自定义')], default='user', max_length=20)),
                ('plugin_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源插件')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('payload_schema', models.JSONField(blank=True, default=dict, verbose_name='载荷 JSON Schema')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '事件类型注册',
                'verbose_name_plural': '事件类型注册',
                'db_table': 'execution_event_type_registry',
            },
        ),
    ]
