# Generated by Django 6.1 on 2026-10-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_restore_squashed_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountfundconfig',
            options={'ordering': ('account_id',), 'verbose_name': '账户资金配置', 'verbose_name_plural': '账户资金配置'},
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='账户名称'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='external_position_symbols',
            field=models.JSONField(blank=True, default=list, verbose_name='外部持仓标的列表'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='has_external_position',
            field=models.BooleanField(default=False, verbose_name='存在外部持仓'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='position_count',
            field=models.IntegerField(default=0, verbose_name='持仓数量'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='position_symbols',
            field=models.JSONField(blank=True, default=list, verbose_name='持仓标的代码列表'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='position_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='持仓最近同步时间'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='position_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='持仓总股数'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='positions',
            field=models.JSONField(blank=True, default=list, verbose_name='持仓明细快照'),
        ),
        migrations.AddField(
            model_name='accountfundconfig',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
    ]
