# Generated by Django 6.1 on 2026-10-09 06:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_alter_accountfundconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfundconfig',
            name='total_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='账户总资金'),
        ),
    ]
