# Generated by Django 6.1 on 2026-08-25 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_eventtyperegistry'),
        ('plans', '0002_initial'),
        ('suites', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiterun',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='suiterun',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='suites.suite'),
        ),
    ]
