# Generated by Django 6.1 on 2026-09-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0010_order_executionlog_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed_report_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
