# Generated by Django 6.1 on 2026-09-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseversion'),
        ('execution', '0011_add_order_processed_report_keys'),
        ('plans', '0004_plan_account_id_plan_allocated_capital'),
        ('suites', '0004_suiteversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('plan', 'Plan 级'), ('suite', 'Suite 级'), ('case', 'Case 级')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='申请额度')),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='已占用金额')),
                ('status', models.CharField(choices=[('active', '生效中'), ('released', '已释放')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='cases.case')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='plans.plan')),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='suites.suite')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='fund_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='execution.fundallocation'),
        ),
        migrations.AddConstraint(
            model_name='fundallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'plan')), fields=('plan',), name='unique_plan_level_allocation'),
        ),
        migrations.AddConstraint(
            model_name='fundallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'suite')), fields=('plan', 'suite'), name='unique_suite_level_allocation'),
        ),
        migrations.AddConstraint(
            model_name='fundallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'case')), fields=('plan', 'suite', 'case'), name='unique_case_level_allocation'),
        ),
    ]
