# Generated by Django 6.1 on 2026-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0012_fundallocation_order_fund_allocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFundConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=64, verbose_name='交易账户ID')),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='账户总资金')),
            ],
            options={
                'verbose_name': '账户资金配置',
                'verbose_name_plural': '账户资金配置',
            },
        ),
    ]
