# Generated by Django 6.1 on 2026-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0013_add_run_status_and_state_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfundconfig',
            name='account_id',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='交易账户ID'),
        ),
    ]
