# Generated by Django 6.1 on 2026-09-09 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0014_account_fund_config_unique'),
        ('plans', '0005_add_run_status_and_state_machine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('in_app', '应用内通知'), ('email', '邮件通知')], max_length=20, unique=True, verbose_name='渠道类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('email_recipients', models.JSONField(blank=True, default=list, verbose_name='邮件收件人列表')),
                ('email_subject_prefix', models.CharField(default='[量化交易系统]', max_length=50, verbose_name='邮件主题前缀')),
                ('min_severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='low', max_length=20, verbose_name='最低告警级别')),
                ('alert_types', models.JSONField(blank=True, default=list, verbose_name='告警类型白名单（空表示全部）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '告警渠道配置',
                'verbose_name_plural': '告警渠道配置',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('order_failed', '订单失败'), ('suite_failed', '策略执行失败'), ('plan_failed', '计划执行失败'), ('risk_violation', '风控违规'), ('system_error', '系统错误')], max_length=50, verbose_name='告警类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决')], default='pending', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='详细消息')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='错误代码')),
                ('in_app_notified', models.BooleanField(default=False, verbose_name='应用内已通知')),
                ('email_notified', models.BooleanField(default=False, verbose_name='邮件已通知')),
                ('notification_error', models.TextField(blank=True, verbose_name='通知错误信息')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_alerts', to='execution.alert')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='plans.plan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('suite_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='execution.suiterun')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'indexes': [models.Index(fields=['-created_at'], name='execution_a_created_ea3862_idx'), models.Index(fields=['status', 'severity'], name='execution_a_status_3bd8f4_idx'), models.Index(fields=['alert_type', '-created_at'], name='execution_a_alert_t_45695e_idx')],
            },
        ),
    ]
