# Generated by Django 6.1 on 2026-09-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0015_alertchannel_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='错误代码'),
        ),
    ]
