# Generated by Django 6.1 on 2026-09-09 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0016_alter_alert_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='execution.order'),
        ),
    ]
