# Generated by Django 6.1 on 2026-09-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0017_alter_alert_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtyperegistry',
            name='base_event_type',
            field=models.CharField(blank=True, help_text='用户自定义事件必须叠加在系统自带事件之上（base_event_type 为系统内置事件名）；插件事件可选叠加。', max_length=50, null=True, verbose_name='叠加基事件'),
        ),
    ]
