# Generated by Django 6.1 on 2026-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('event_condition', models.JSONField(blank=True, default=dict)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aggregate_method', models.CharField(choices=[('weighted_sum', '加权求和'), ('vote', '投票'), ('and', '逻辑与'), ('or', '逻辑或')], default='weighted_sum', max_length=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('allocated_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='占用资金')),
                ('run_status', models.CharField(choices=[('new', '未运行'), ('running', '运行中'), ('done', '已完成'), ('interrupt', '已中断')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cases', models.ManyToManyField(blank=True, related_name='suites', to='cases.case')),
            ],
        ),
    ]
