# Generated by Django 6.1 on 2026-08-24 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suite',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='suites.suite'),
        ),
        migrations.AddField(
            model_name='edge',
            name='from_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='suites.suite'),
        ),
        migrations.AddField(
            model_name='edge',
            name='to_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='suites.suite'),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('from_suite', 'to_suite', 'condition')},
        ),
    ]
