# Generated by Django 6.1 on 2026-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suites', '0004_suiteversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='allocated_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='占用资金'),
        ),
        migrations.AddField(
            model_name='suite',
            name='run_status',
            field=models.CharField(choices=[('new', '未运行'), ('running', '运行中'), ('done', '已完成'), ('interrupt', '已中断')], default='new', max_length=10),
        ),
    ]
