# Generated by Django 6.1 on 2026-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AStockKLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(verbose_name='成交量（股数）')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额（元）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adj_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='复权因子')),
                ('limit_up', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='涨停价')),
                ('limit_down', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='跌停价')),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='换手率%')),
            ],
            options={
                'verbose_name': 'A股K线',
                'verbose_name_plural': 'A股K线',
                'db_table': 'kline_a_stock',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('source_type', models.CharField(choices=[('akshare', 'AkShare'), ('tushare', 'TuShare'), ('tdx', 'TDX'), ('yfinance', 'YFinance')], max_length=20)),
                ('endpoint', models.URLField(blank=True, null=True)),
                ('auth_info', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HKStockKLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(verbose_name='成交量（股数）')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额（元）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='前收盘价')),
                ('currency', models.CharField(default='HKD', max_length=10, verbose_name='货币单位')),
            ],
            options={
                'verbose_name': '港股K线',
                'verbose_name_plural': '港股K线',
                'db_table': 'kline_hk_stock',
            },
        ),
        migrations.CreateModel(
            name='KLineSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('daily', '日线'), ('minute', '分钟线')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('records_added', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
