# Generated by Django 6.1 on 2026-08-24 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasources', '0001_initial'),
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeSnapshot',
            fields=[
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='snapshot', serialize=False, to='watchlists.symbol')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='最新价')),
                ('change', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='涨跌幅%')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额')),
                ('high', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='日内最高')),
                ('low', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='日内最低')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='开盘价')),
                ('pre_close', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='昨收价')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='astockkline',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='watchlists.symbol'),
        ),
        migrations.AddField(
            model_name='hkstockkline',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='watchlists.symbol'),
        ),
        migrations.AddField(
            model_name='klinesynclog',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='watchlists.symbol'),
        ),
        migrations.AlterUniqueTogether(
            name='astockkline',
            unique_together={('symbol', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='hkstockkline',
            unique_together={('symbol', 'date')},
        ),
        migrations.CreateModel(
            name='USStockKLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(verbose_name='成交量（股数）')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额（元）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('split_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='拆分因子')),
                ('pre_market_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='盘前价')),
                ('after_hours_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='盘后价')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='watchlists.symbol')),
            ],
            options={
                'verbose_name': '美股K线',
                'verbose_name_plural': '美股K线',
                'db_table': 'kline_us_stock',
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
