# Generated by Django 6.1 on 2026-09-08 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_initial'),
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalCacheMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时点')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='缓存命中次数')),
                ('miss_count', models.PositiveIntegerField(default=0, verbose_name='缓存未命中次数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundamental_cache_meta', to='watchlists.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asof', models.DateTimeField(db_index=True, verbose_name='数据时点')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='基本面指标快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamental_snapshots', to='watchlists.symbol')),
            ],
            options={
                'verbose_name': '基本面快照',
                'verbose_name_plural': '基本面快照',
                'ordering': ('-asof',),
                'constraints': [models.UniqueConstraint(fields=('symbol', 'asof'), name='unique_fundamental_symbol_asof')],
            },
        ),
    ]
