# Generated by Django 6.1 on 2026-09-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_add_fundamental_snapshot_cache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
