"""
Django settings for quant_engine project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
# pylint: disable=C0413,C0411,w0401,w0614,w0611
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
PROJECT_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(PROJECT_DIR)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-7ya^@-)^rrgxn!!)r(r)#^eo^zu3d_#r$0ibpyv@$_a$nmvgdp'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.cases',
    'apps.suites',
    'apps.plans',
    'apps.execution',
    'apps.watchlists',
    'apps.datasources',
    'apps.users',
    'apps.monitoring',

    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'arcis.django.ArcisMiddleware',
]

ROOT_URLCONF = 'quant_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quant_engine.wsgi.application'


# Database is configured per environment in dev.py and production.py.
# See: quant_engine/settings/dev.py and quant_engine/settings/production.py

KLINE_DB_ALIAS = 'kline'
FUNDAMENTALS_ENABLED = False

# 分时监控内部更新器（随 Django 服务启动；禁止单独的更新命令）
import os  # noqa: E402  # pylint: disable=wrong-import-position

MONITORING_UPDATER_ENABLED = os.getenv('MONITORING_UPDATER_ENABLED', '1').lower() in {'1', 'true', 'yes'}
MONITORING_UPDATER_INTERVAL = int(os.getenv('MONITORING_UPDATER_INTERVAL', '60'))

# 执行日志生命周期（N-04）：默认保留 30 天，Scheduler 每日自动清理一次
EXECUTION_LOG_RETENTION_ENABLED = os.getenv('EXECUTION_LOG_RETENTION_ENABLED', '1').lower() in {'1', 'true', 'yes'}
EXECUTION_LOG_RETENTION_DAYS = int(os.getenv('EXECUTION_LOG_RETENTION_DAYS', '30'))

# DRF 全局配置
REST_FRAMEWORK = {
    # N-01：所有列表接口统一分页
    'DEFAULT_PAGINATION_CLASS': 'quant_engine.pagination.StandardResultsPagination',
    'PAGE_SIZE': 20,
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'assets/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / 'static' / 'assets']


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025
EMAIL_USE_TLS = False
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'noreply@example.com'

CORS_ALLOW_ALL_ORIGINS = True
AUTH_USER_MODEL = 'users.User'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'file': {'level': 'DEBUG','class': 'logging.FileHandler','filename': 'logs/django.log'}},
    'loggers': {'django': {'handlers': ['file'],'level': 'DEBUG','propagate': True}}
}

# SQLite 连接调优（WAL + busy_timeout）：多进程开发栈（run_dev_stack：Django + MCP）
# 并发访问 SQLite 时消除 "database is locked"。仅 SQLite 生效，生产 MariaDB 不受影响。
from quant_engine import db_tuning  # noqa: E402,F401  pylint: disable=unused-import

