# Generated by Django 6.1 on 2026-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('signal', '信号节点'), ('filter', '过滤器'), ('verdict', '裁决节点'), ('executor', '执行器')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20)),
                ('run_status', models.CharField(choices=[('new', '未运行'), ('running', '运行中'), ('done', '已完成'), ('failed', '失败')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('signal', '信号节点'), ('filter', '过滤器'), ('verdict', '裁决节点'), ('executor', '执行器')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
    ]
