# Generated by Django 6.1 on 2026-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='run_status',
            field=models.CharField(choices=[('new', '未运行'), ('running', '运行中'), ('done', '已完成'), ('failed', '失败')], default='new', max_length=10),
        ),
    ]
