# Generated by Django 6.1 on 2026-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('time', '时间驱动'), ('event', '事件驱动'), ('manual', '手动触发')], default='time', max_length=20)),
                ('cron_expr', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol_scope', models.JSONField(default=dict)),
                ('exec_mode', models.CharField(choices=[('serial', '串行'), ('parallel', '并行'), ('fail_stop', '失败停止')], default='serial', max_length=20)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
