# Generated by Django 6.1 on 2026-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('time', '时间驱动'), ('event', '事件驱动'), ('manual', '手动触发')], default='time', max_length=20)),
                ('cron_expr', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('exec_mode', models.CharField(choices=[('serial', '串行'), ('parallel', '并行'), ('fail_stop', '失败停止')], default='serial', max_length=20)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('account_id', models.CharField(blank=True, max_length=64, verbose_name='交易账户ID')),
                ('allocated_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='占用资金总额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('run_status', models.CharField(choices=[('new', '未运行'), ('running', '运行中'), ('done', '已完成'), ('interrupt', '已中断')], default='new', max_length=10)),
                ('suite_start_mode', models.CharField(choices=[('auto', 'Plan 启动时自动启动 Suite'), ('manual', '手动启动 Suite')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
    ]
