# Generated by Django 6.1 on 2026-09-28 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('suites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='root_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='suites.suite'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='plans.plan'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='unique_plan_version'),
        ),
    ]
