# Generated by Django 6.1 on 2026-09-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='risk_allowed_sessions',
            field=models.JSONField(blank=True, help_text='形如 [[9,30,11,30],[13,0,15,0]] 或 [[[9,30],[11,30]]]；留空用默认 A 股时段', null=True, verbose_name='交易时段窗口'),
        ),
        migrations.AddField(
            model_name='plan',
            name='risk_max_account_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='下单前校验账户可用资金是否覆盖本笔金额；需接账户快照来源', max_digits=16, null=True, verbose_name='账户可用资金上限'),
        ),
        migrations.AddField(
            model_name='plan',
            name='risk_max_daily_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='按当日已挂用的委托单金额（price × volume）累计；留空不限制', max_digits=16, null=True, verbose_name='每日累计金额上限'),
        ),
        migrations.AddField(
            model_name='plan',
            name='risk_max_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='单笔金额上限'),
        ),
        migrations.AddField(
            model_name='plan',
            name='risk_max_order_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='单笔数量上限'),
        ),
        migrations.AddField(
            model_name='plan',
            name='risk_max_position_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='总仓位金额上限'),
        ),
        migrations.AddField(
            model_name='plan',
            name='risk_max_position_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='总仓位数量上限'),
        ),
        migrations.AddField(
            model_name='plan',
            name='risk_position_mode',
            field=models.CharField(choices=[('both', '双向'), ('long_only', '仅做多'), ('short_only', '仅做空'), ('flat', '不开仓')], default='both', help_text='both=双向 / long_only=仅做多 / short_only=仅做空 / flat=不开仓', max_length=10, verbose_name='持仓方向限制'),
        ),
    ]
