# Generated by Django 6.1 on 2026-09-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_planversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='account_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='交易账户ID'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allocated_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='占用资金总额'),
        ),
    ]
