# Generated by Django 6.1 on 2026-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_account_id_plan_allocated_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='run_status',
            field=models.CharField(choices=[('new', '未运行'), ('running', '运行中'), ('done', '已完成'), ('interrupt', '已中断')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='suite_start_mode',
            field=models.CharField(choices=[('auto', 'Plan 启动时自动启动 Suite'), ('manual', '手动启动 Suite')], default='manual', max_length=10),
        ),
    ]
