# Generated by Django 6.1 on 2026-09-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='采样时间(UTC)')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='现价')),
                ('change', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='涨跌幅%')),
                ('volume', models.BigIntegerField(default=0, verbose_name='累计成交量')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='累计成交额')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='均价')),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='日内最高')),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='日内最低')),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='开盘价')),
                ('pre_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='昨收价')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraday_points', to='watchlists.symbol', verbose_name='标的')),
            ],
            options={
                'verbose_name': '分时监控点',
                'verbose_name_plural': '分时监控点',
                'ordering': ('symbol', 'ts'),
                'indexes': [models.Index(fields=['symbol', '-ts'], name='idx_intraday_symbol_ts')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'ts'), name='uniq_intraday_symbol_ts')],
            },
        ),
    ]
