# Generated by Django 6.1 on 2026-09-28 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intradaypoint',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraday_points', to='watchlists.symbol', verbose_name='标的'),
        ),
        migrations.AddIndex(
            model_name='intradaypoint',
            index=models.Index(fields=['symbol', '-ts'], name='idx_intraday_symbol_ts'),
        ),
        migrations.AddConstraint(
            model_name='intradaypoint',
            constraint=models.UniqueConstraint(fields=('symbol', 'ts'), name='uniq_intraday_symbol_ts'),
        ),
    ]
